CREATE TABLE `projeto`.`dim_produto` (
  `sk_produto` INT NOT NULL,
  `cd_produto` VARCHAR(30) NULL,
  `isbn_produto` VARCHAR(13) NULL,
  `cd_historico` VARCHAR(30) NULL,
  `cd_mae` VARCHAR(30) NULL,
  `no_produto` VARCHAR(120) NULL,
  `cd_tipo_publicacao` VARCHAR(6) NULL,
  `no_tipo_publicacao` VARCHAR(100) NULL,
  `dt_publicacao` DATE NULL,
  `cd_situacao` VARCHAR(6) NULL,
  `no_situacao` VARCHAR(100) NULL,
  `cd_grupo` VARCHAR(4) NULL,
  `no_grupo` VARCHAR(30) NULL,
  `cd_area` VARCHAR(6) NULL,
  `no_area` VARCHAR(100) NULL,
  PRIMARY KEY (`sk_produto`));